// <auto-generated />
using System;
using DupeDetectorWorkerService.database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DupeDetectorWorkerService.Migrations
{
    [DbContext(typeof(DupeDBContext))]
    partial class DupeDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("DuplicateFile", b =>
                {
                    b.Property<Guid>("DuplicateFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Md5CheckSum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DuplicateFileId");

                    b.ToTable("DuplicateFile");
                });
#pragma warning restore 612, 618
        }
    }
}
